id: P006841
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20239
  title: བོད་ཡིག་ཚེག་སྡེབ་བསླབ་པའི་ཐབས་མཆོག
  author: ''
  volumes:
    cf6165c1bbf54b819071195f81f8bf4c:
      image_group_id: I8LS20241
      title: ''
      volume_number: 1
      total_pages: 93
      base_file: v001.txt
